danskernesdigitalebibliotek/dpl-go

- __tests__/search.test.ts
- app/search/fetchSearchResult.server.ts
- components/pages/searchPageLayout/SearchPageLayout.tsx
- components/pages/searchPageLayout/helper.ts
- components/shared/searchFilters/SearchFiltersColumn.tsx
- components/shared/searchFilters/helper.ts
- lib/config/resolvers/search.ts
https://reload.atlassian.net/browse/DDFBRA-142
Just a quick cleanup suggestion. 
* Since most of the query parameters are being repeated 3 times, I think it is better to define them once and reuse them.
* Moved some other functionality to the helper file as well.
* Deleted the `formatFacetTerms()` function which did not seem to be used anywhere.
* Moved search facet definition into config
* Wrote test for the various functionalities
> Consolidate search functionality

- .eslintrc.json
- .github/workflows/prettier-check.yml
- .prettierignore
- Taskfile.yml
- app/auth/callback/unilogin/schemas.ts
- app/auth/login/unilogin/route.ts
- app/auth/session/route.ts
- app/page.tsx
- components/shared/badge/BadgeButton.tsx
- components/shared/workCard/WorkCardAvailabilityItem.tsx
- lib/fetchers/types.ts
- lib/getQueryClient.ts
- lib/helpers/helper.cn.ts
- lib/providers/ReactQueryProvider.tsx
- lib/rest/publizon-api/publizon-adapter.yaml
- lib/types/session.ts
- package.json
- postcss.config.mjs
- vitest.config.ts
- yarn.lock
https://reload.atlassian.net/browse/DDFBRA-179
Adds a new Github workflow to check for Prettier formatting issues. 
Use `yarn format:write` to fix any found issues.
> Add Prettier check to pipeline

- app/auth/callback/unilogin/route.ts
- app/auth/logout/route.ts
`Response.redirect` needs absolute url in order to function correctly
> Use absolute  urls in unilogin flow redirects

- components/shared/workCard/WorkCard.tsx
- components/shared/workCard/WorkCardImage.tsx
https://reload.atlassian.net/browse/DDFBRA-130
fixed a bug on the search result page
> fix: improve loading state handling and image rendering in WorkCard image

- __tests__/search.test.ts
- components/pages/searchPageLayout/SearchPageLayout.tsx
- components/pages/searchPageLayout/helper.ts
- components/shared/searchFilters/SearchFiltersColumn.tsx
- components/shared/searchFilters/SearchFiltersDesktop.tsx
- components/shared/searchFilters/SearchFiltersMobile.tsx
- components/shared/searchFilters/helper.ts
- components/shared/searchInput/SearchInput.tsx
- lib/config/dpl-cms/dplCmsConfig.ts
- lib/getQueryClient.ts
- lib/machines/search/debug.ts
- lib/machines/search/helpers.ts
- lib/machines/search/search.machine.setup.ts
- lib/machines/search/search.machine.ts
- lib/machines/search/useSearchMachineActor.tsx
- lib/providers/ReactQueryProvider.tsx
https://reload.atlassian.net/browse/DDFBRA-130
This PR adresses the behaviour that changed after the transition to use Xstate in searching/filtering.
Things being handled:
* The skeleton screen on load more
* The behaviour around deleting last character in the search field (which was actually working as intended, but I agree in an oddly manner 😆 )
* The weird issue about FBI sending one kind of facet names from service and expecting another as input (lix -> lixRange)
* Changing the way filters where toggled and detected as being active (that was not handled after the inital xstate introduction)
* Allowing the end user to type and filter while requests are ongoing
> Xstate fixes

- components/pages/searchPageLayout/SearchPageLayout.tsx
https://reload.atlassian.net/browse/DDFBRA-246
Look in the title
> fix: show ghost loading both when loading more results and initial results

- components/pages/searchPageLayout/SearchPageLayout.tsx
https://reload.atlassian.net/browse/DDFBRA-291
Check the title
> feat: make the loadmore ref trigger 500px before the end of the list

- app/search/page.tsx
https://reload.atlassian.net/browse/DDFBRA-287
This PR makes the user go directly to search result page when making a search
> fix: remove await from prefetch functions in search page for improved perceived performance when loading search result page

- lib/machines/search/search.machine.setup.ts
- lib/machines/search/search.machine.ts
https://reload.atlassian.net/browse/DDFBRA-286
This PR introduces a fix to the search result page where search result dont get updated when clicking a tag on the material page
> fix: search machine to have a specific method for loading more results

- .github/workflows/e2e-test.yml
- .gitignore
- README.md
- app/auth/callback/unilogin/route.ts
- app/page.tsx
- components/global/header/Header.tsx
- cypress.config.ts
- cypress/cypress.d.ts
- cypress/e2e/frontpage.cy.ts
- cypress/support/commands.ts
- cypress/support/constants.ts
- cypress/support/e2e.ts
- lib/session/session.ts
- package.json
- tsconfig.json
- yarn.lock
https://reload.atlassian.net/browse/DDFBRA-233
This PR adds the e2e framework Cypress to the project and includes a basic test that verify that the application builds successfully and that the frontpage renders a header and a footer. 
Future work will include mocking FBI data and testing core user journeys
> Introduce Cypress

- .github/workflows/publish-source.yml
See if this solves our issue with Github action runner that is running out of space:
https://github.com/marketplace/actions/free-disk-space-ubuntu
https://reload.atlassian.net/browse/DDFBRA-340
It seems like using [Free Disk Space (Ubuntu) action
](https://github.com/marketplace/actions/free-disk-space-ubuntu) helps solving the Github Action runner "System.IO.IOException: No space left on device" error.
Error can be seen [here](https://github.com/danskernesdigitalebibliotek/dpl-go/actions/runs/12688155533).
[This](https://github.com/danskernesdigitalebibliotek/dpl-go/actions/runs/12690334230) is a succesful run after adding the Free Disk Space action.
> Solve "System.IO.IOException: No space left on device" error

- docs/README.md
- docs/architecture/adr-001-configuration.md
- docs/architecture/adr-002-xstate.md
https://reload.atlassian.net/browse/DDFBRA-249
Added Architectural Decision Rocords describing the choices around configuration handling and the Xstate state machine.
> Add documentation about Xstate and configuration handling

- components/shared/searchInput/SearchInput.tsx
https://reload.atlassian.net/jira/software/c/projects/DDFBRA/boards/498?assignee=unassigned&selectedIssue=DDFBRA-350
Read the title
> refactor: change keydown handling in SearchInput component to navigate using input ref value

- __tests__/search.test.ts
- codegen.ts
- components/pages/workPageLayout/WorkPageHeader.tsx
- components/pages/workPageLayout/WorkPageLayout.tsx
- components/pages/workPageLayout/helper.ts
- components/shared/workCard/helper.ts
- lib/graphql/generated/fbi/graphql.tsx
- lib/helpers/ids.ts
https://reload.atlassian.net/browse/DDFBRA-234
As a part of my work on Cypress and type safety, I discovered that it would make sense to use string unions instead of enums, as they can make our code more concise and readable.
> Codegen: Use unions instead of enums

- docs/research/ereolengo/unilogin_publizon_models_and_relations.md
https://reload.atlassian.net/browse/DDFBRA-249
The wrong title hierarchy resulted in a bad rendering of the menu in dpl-docs.
> Fixing title hierarchy in documentation

- .env.example
- app/auth/callback/adgangsplatformen/loadUserToken.ts
- codegen.ts
- components/global/header/ProfileButton.tsx
- graphql-codegen-scripts/post-process-dpl-cms-graphql.ts
- lib/config/dpl-cms/dplCmsConfig.ts
- lib/config/dpl-cms/useGetDplCmsLoginUrls.ts
- lib/graphql/fetchers/dpl-cms.fetcher.ts
- lib/graphql/generated/dpl-cms/graphql.tsx
- lib/graphql/queries/configuration.dpl-cms.graphql
- lib/graphql/queries/login-urls.dpl-cms.graphql
- package.json
- yarn.lock
https://reload.atlassian.net/browse/DDFBRA-353
The work here is not tied to the Jira task itself but is needed for the login functionality in general.
The added functionality fetches the Adgangsplatformen login url for the Go application.
A post dpl-cms API graphql codgen script has been added that replaces `RequestInit["headers"]` with `RequestInit & { next?: NextFetchRequestConfig }` since we need to be able to pass the nextjs options to the fetcher in order to control the cache.
> Providing Adgangslogin url to Go + fixing dpl-cms options type

- lib/machines/search/useSearchMachineActor.tsx
In order to prevent lint error in build
The linter wants us to add all referenced deps in useEffect.
And an unused variable is removed.
> Remove lint error in build

- lagoon/start.sh
https://reload.atlassian.net/browse/DDFBRA-463
We cannot use an extra "go." subdomain in pr environments so we need to use "go-" prefix instead.
This fix makes it possible to use the [nginx annotation setting ](https://github.com/danskernesdigitalebibliotek/dpl-cms/blob/3357a502ccf5bdc59a0c51f4f2b16b905c698259/.lagoon.yml#L171-L173) we need for setting te go-session cookie .
> Set NEXT_PUBLIC_APP_URL differently depending on environment

- lagoon/node.dockerfile
- lagoon/start.sh
https://reload.atlassian.net/browse/DDFBRA-463
This seems to improve the build speed which we need right now in order to prevent  kubernetes/Lagoon in rebuilding because of readiness timeout
> No server source maps

- lagoon/start.sh
- next.config.mjs
This is only temporary but we want to see if we can get a faster build timer and go below the readiness threshold of k8s.
> Try to ignore ts and eslint checks when building

- lagoon/start.sh
Since that is how we (at least for now) format the cms urls
> Make sure that cms url resolving looks after `cms-`

- app/user/profile/page.tsx
Both LogoutButton and DebuggingSession components need the Suspense. We could take a look why in the future. Has something to do with that they both are using useSearchParams
> Reorganize Suspense on user profile page

- app/layout.tsx
- styles/globals.css
[DDFBRA-448](https://reload.atlassian.net/browse/DDFBRA-448)
When `duration-dark-mode` and `transition-all` is applied to the body element, it will also affect components in storybook, which causes the background to animate when loading a story. This causes axe to register the wrong colors, as colors are being animated while axe runs its checks.
This PR moved those mentioned classes to the Nextjs layout so stories will not have the transition effect.
> Fix inaccurate automatic accessibility test

- components/pages/workPageLayout/LoanMaterialModal.tsx
- components/pages/workPageLayout/WorkPageButtons.tsx
https://reload.atlassian.net/browse/DDFBRA-379
This PR fixes some small bugs connected to work page buttons:
- texts between material types (Læs lydbog f.e.)
- loading state in the "confirm loan" button, which wasn't showing the loading icon
-
-
> Fix "read podcast"

- lib/machines/search/queries.ts
- lib/machines/search/types.ts
https://reload.atlassian.net/browse/DDFBRA-485
This PR introduces a hardcoded filter to search results that ensures that only materials for children is fetched
> feat: Add hardcoded childrenOrAdults filter to search queries

- app/user/profile/FindBookButton.tsx
- app/user/profile/LoanSlider.tsx
- app/user/profile/LogoutButton.tsx
- app/user/profile/ProfilePageLayout.tsx
- components/shared/button/ButtonWithLoadingStateHoc.tsx
- components/shared/sheet/LoginButton.tsx
- components/shared/sheet/LoginSheet.tsx
https://reload.atlassian.net/browse/DDFBRA-508
Introducing a common way of handling loading state when clicking buttons that triggers longer loading processes.
And implements it on:
* Logout button
* "Find a book" button
* Login button
> Common way of handling "loading" buttons

- app/ap-service/[[...slug]]/route.ts
Then we do not need to have any content-type header eg. logic. We simply pass along what we get.
> Pass original request headers through to service

- __tests__/env.test.ts
- __tests__/helpers.ts
Sometimes we expect a test to throw errors, which sometimes also logs messages to the console. This will lead to confusion, because it looks like unitended errors while testing.
With this custom function we can silence those expected messages.
> Added vitest helper function to run tests silently

- app/ap-service/[[...slug]]/route.ts
- lib/config/resolvers/services.ts
- lib/graphql/fetchers/fbi.fetcher.ts
- lib/helpers/ap-service.ts
- lib/helpers/bearer-token.ts
- lib/rest/cover-service-api/mutator/fetcher.ts
- lib/rest/fbs/mutator/fetcher.ts
- lib/rest/publizon/adapter/mutator/fetcher.ts
https://reload.atlassian.net/browse/DDFBRA-508
This PR should be merged after [this one](https://github.com/danskernesdigitalebibliotek/dpl-go/pull/208) has been reviewed because it contains a lot of the same commits.
The main focus in this PR is to make sure that Adgangsplatform services that are not dependent on an authorized user (aka only uses library token) do NOT use the ap service proxy, because we never need to attach the user token server side.
Right now the cover service is a service that only needs the library token and therefor is not being proxied.
But this PR also introduces a function for resolving the auth header in the AP service fetchers, so it is done in a uniform way.
And this PR makes sure that it is always possible to override the fetch headers from outside the …
> Do not use AP proxy on useLibraryTokenAlways services

- components/pages/workPageLayout/WorkPageHeader.tsx
- components/shared/workCard/WorkCard.tsx
https://reload.atlassian.net/browse/DDFBRA-566
This PR fixes the issue where pubhub calls are failing since theres no pubhub data on physical materialtypes
> Ddfbra 566 nogle bla titel opslag giver 400

- __tests__/__snapshots__/pubhub.test.ts.snap
- app/pubhub/v1/user/loans/(lib)/schemas.ts
- app/pubhub/v1/user/loans/route.ts
- app/user/profile/ProfilePageLayout.tsx
- app/user/profile/SupportId.tsx
https://reload.atlassian.net/browse/DDFBRA-421
This PR adds support ID for unilogin + bib users on the profile page.
-
> Add support ID to profile page

- __tests__/middleware.test.ts
- __tests__/pubhub.test.ts
- app/ap-service/[[...slug]]/route.ts
- app/user/profile/ProfilePageLayout.tsx
- app/work/[id]/page.tsx
- components/pages/workPageLayout/WorkPageLayout.tsx
- components/shared/coverPicture/CoverPicture.tsx
- lib/helpers/ap-service.ts
- lib/helpers/bearer-token.ts
- lib/helpers/library-token.ts
- lib/helpers/middleware.ts
- lib/rest/cover-service-api/mutator/fetcher.ts
- lib/rest/fbs/mutator/fetcher.ts
- lib/rest/publizon/adapter/mutator/fetcher.ts
- lib/session/session.ts
- middleware.ts
https://reload.atlassian.net/browse/DDFBRA-563
The loading flow on the front page and on the search page was slow and seemed like it was waiting for requests to be fulfilled.
I found out that the functionality to get the librarytoken had turned into a server action and was called over and over again.
The architecture around the library token has now been restructured. It is still saved as a cookie so we can take advantage of the general principle of cookies expiring in browsers. But the value from the cookie is retrieved from the `getSession` function that is now a singe entrypoint for getting both the user and the library token. It means we do not have to struggle wit cookie fetching in a mixed client/server environment and we handle the user library token lookup in the same manner.
Also …
> Solve weird cascade loading on front and search page

- lib/helpers/dpl-cms-content.ts
> Goodbye /go cms url prefix for go CMS content

- cypress/factories/dpl-cms/getPageByPathQuery/go-frontpage.ts
Without this our tsc check in CI thrwos an error which prevents the `build source` workflow to build the app.
> The __typename of the fetched entity has been added

- app/(routes)/auth/session/route.ts
- removes dynamic export from session route 
- - It's dynamic by default in the latest canary version of Next.js
- - dynamicio doesn't support this option
-
-
-
> Fix failing login

- app/(routes)/auth/session/route.ts
- lib/session/session.ts
- package.json
- yarn.lock
https://reload.atlassian.net/browse/DDFBRA-635
* Solving login issue with use of [unstable_rethrow](https://nextjs.org/docs/app/api-reference/functions/unstable_rethrow)
* Upgrade to latest Next.js 15.4.0 canary version
* Reintroduce `force-dynamic` on session route (to be honest I am not sure if this is necessary, but due to the long waiting time for deployments, I did not have time to test it)
> Reintroduce force dynamic on session route with nextjs upgrade

- lagoon/start.sh
https://reload.atlassian.net/browse/DDFBRA-582
Use lagoon env variables for cms routes
In the docker file we can make use of LAGOON_ROUTE which always point to the cms. And LAGOON_DOMAIN seems to be the same without the protocol.
> Use lagoon env variables for cms routes

- app/(pages)/user/profile/LoanCard.tsx
- components/pages/workPageLayout/WorkPageHeader.tsx
- components/shared/coverPicture/CoverPicture.stories.tsx
- components/shared/coverPicture/CoverPicture.tsx
- components/shared/loanMaterialModal/LoanMaterialModal.tsx
- components/shared/workCard/WorkCard.tsx
https://reload.atlassian.net/browse/DDFBRA-700
This PR changes the image element in `CoverPicture.tsx` to use a simple `<img>` element instead of the cached <Image>.
By doing this, we also need to generate our own `srcset`, by using the different size variants coming from FBI. 
This also requires the component to receive the full covers object.
> Use cover object to generate `srcset` to load directly from FBI

- components/paragraphs/Video/Video.tsx
- components/paragraphs/VideoBundle/VideoBundle.tsx
- components/shared/coverPicture/CoverPicture.tsx
- components/shared/image/ImageBase.tsx
- components/shared/publizonPlayer/PublizonPlayer.tsx
- components/shared/workCard/WorkCardStackedWithCaption.tsx
- cypress/e2e/frontpage.cy.ts
https://reload.atlassian.net/browse/DDFBRA-701
To improve performance on pages with a lot of pictures, it is necessary to lazy load images only when they appear in the browser viewport. 
This can also be done for iframes, which are uses to display vidoes.
We also discovered that for every rerender of the `WorkCardStackedWithCaption.tsx` component, it would re-fetch all images for each pagination in the carousel. By refactoring it, we only render the currently shown material cover.
> Lazy load images and iframes

- lib/config/dpl-cms/dplCmsConfig.ts
Since we get both prerender errors and errors from middleware when using it.
We need to solve it in the near future.
>  Skip caching of dpl cms private/public for now

- lib/config/dpl-cms/dplCmsConfig.ts
To emphasize that whenever config is needed we cannot prerender pages depending on it.
> Await connection() when fetching config

- .env.production
- lib/helpers/publizon.ts
https://reload.atlassian.net/browse/DDFSAL-401
- Removed fallback variables from the .env.production
- Changed `UNLILOGIN_PUBHUB_RETAILER_KEY_CODE` to be loaded from env variables instead of dpl-cms
> Ddfsal 401 fjerne env production fil
