tsconfig.json
When Nextjs is running in dev mode it adds some config changes in tsconfig.
=> Add Nextjs tsconfig moderations

components/global/header/ProfileButton.tsx, components/shared/button/Button.tsx, components/shared/sheet/LoginSheet.tsx, hooks/useSession.ts, styles/globals.css
https://reload.atlassian.net/browse/DDFBRA-112
This PR fixes styling connected to logging-in so that it work between day & night mode + is accessible.
I also changes "loading" into "isLoading" so that it makes sense that it's a boolean 😉 
-
-
=> Fix various styling inconsistencies

app/layout.tsx, components/global/gridHelper/GridHelper.tsx, lib/helpers/visibility.tsx
Added a hoc for controlling development/production visibility of a component.
Take it or leave it.
=> With visibility

components/pages/searchPageLayout/SearchPageLayout.tsx, components/shared/searchFilters/SearchFiltersColumn.tsx, components/shared/searchFilters/helper.ts
https://reload.atlassian.net/browse/DDFBRA-162
This PR fixes broken filters. The filters weren't filtering due to changes in the FBI API.
-
-
=> Fix broken filters on search page

lib/rest/cover-service-api/mutator/fetcher.ts
-
Remove unnecessary "Accept-Version" header from cover service fetcher
-
-
=> Fix CORS error on covers

components/shared/icon/Icon.tsx
-
Enable dynamic SVG imports in Icon component
-
-
=> Enable dynamic SVG imports in Icon component

components/shared/workCard/WorkCard.tsx, lib/helpers/helper.routes.ts
https://reload.atlassian.net/browse/DDFBRA-159
Add a resolver function that streamline the internal routes in the app
=> feat: add route resolver for work URLs and update WorkCard component

components/shared/fonts/Fonts.stories.tsx, components/shared/fonts/Fonts.tsx
https://reload.atlassian.net/browse/DDFBRA-177
This PR contains a component for showing all used fonts in the project and a story to ensure that these are not changing throughout development.
=> feat: add Fonts component and Storybook stories for typography display and test

.gitignore, package.json
https://reload.atlassian.net/browse/DDFBRA-112
Enable https based development
Following this article:
https://vercel.com/guides/access-nextjs-localhost-https-certificate-self-signed
=> Enable https based development

.env.example, .env.test, lib/config/resolvers/service.unilogin.ts
No issue
- fixed typo in the env files
- public app url is now https to support unilogin
=> fix: typo in the env files

app/layout.tsx, components/pages/workPageLayout/WorkPageButtons.tsx, components/pages/workPageLayout/WorkPageHeader.tsx, components/shared/coverPicture/CoverPicture.tsx, components/shared/workCard/WorkCard.tsx, styles/globals.css
https://reload.atlassian.net/browse/DDFBRA-172
This PR contains some minor adjustment to the styling of workpage and coverPicture
=> fix: add minor adjustments to the workpage header / coverPicture

components/pages/searchPageLayout/SearchPageLayout.tsx, lib/machines/search/search.machine.setup.ts, lib/machines/search/search.machine.ts
https://reload.atlassian.net/browse/DDFBRA-246
fix: bug that returns an empty search result when navigation with native browser navigation buttons
fix: reset offset when making new search and filtering
feat: add initial context as an globally accessible reference
=> Ddfbra 246 fix missing search results

app/page.tsx, components/videoPlayer/VideoPlayer.tsx, package.json
https://reload.atlassian.net/browse/DDFBRA-239
This PR includes initial work on video component using the videotool provider
=> feat: add VideoPlayer component and update Home page layout

app/auth/token/refresh/route.ts, app/work/[id]/read/page.tsx, next.config.mjs
https://reload.atlassian.net/browse/DDFBRA-274
Fix some async API changes in NextJs 15
For some reason these problems was not caught by our ci checks.
=> Fix some async API changes in NextJs 15

components/global/footer/Footer.tsx, components/pages/workPageLayout/WorkPageHeader.tsx, components/pages/workPageLayout/WorkPageLayout.tsx, components/shared/infoBox/InfoBox.stories.tsx, components/shared/infoBox/InfoBox.tsx, components/shared/infoBox/InfoBoxDetails.stories.tsx, components/shared/infoBox/InfoBoxDetails.tsx, components/shared/infoBox/InfoBoxItem.tsx, lib/graphql/fragments/manifestation.fbi.graphql, lib/graphql/generated/fbi/graphql.tsx, lib/mocks/manifestation/infoBox.mock.ts, lib/mocks/work/infoBox.mock.ts, styles/globals.css
https://reload.atlassian.net/browse/DDFBRA-170
This PR:
- adds the InfoBoxDetails component 
- adjusts some styling 
- fixes conditional rendering of work description items
- adds storied for InfoBox & InfoBoxDetails components
I can't figure out why the InfoBox stories are full width and InfoBoxDetails are not, as they're styled in the same way. Pls if anyone knows, do tell :))
=> Show work details info

docs/research/ereolengo/unilogin_publizon_models_and_relations.md
https://reload.atlassian.net/browse/DDFBRA-247
Adding research documentation about Publizon login and loan requests at the current "eReolen GO!" live site.
=> Add documentation about eReolen GO!

components/pages/workPageLayout/WorkPageButtons.tsx, components/shared/infoBox/InfoBoxDetails.tsx
https://reload.atlassian.net/browse/DDFBRA-336
Small changes.
-
-
=> Rename "Omfang" to "Længde" in InfoBoxDetails component

components/shared/infoBox/InfoBox.tsx, components/shared/infoBox/InfoBoxItem.tsx
https://reload.atlassian.net/browse/DDFBRA-339
This PR makes it possible to link to a search result upon clicking on the name of a series on material page.
-
-
=> Link to search on clicking on series name on work page

styles/globals.css
https://reload.atlassian.net/browse/DDFBRA-339
This PR makes it possible to link to a search result upon clicking on the name of a series on material page.
-
-
=> fix: adjust text underline animation on hover

.github/workflows/accessibility-test.yml, .github/workflows/chromatic.yml, .storybook/main.ts, components/shared/fonts/Fonts.tsx
none
Test env variables in storybook
=> Ddfbra 334 podcast er altid bla titler

components/shared/button/Button.tsx
https://reload.atlassian.net/browse/DDFBRA-355
We want to be able to distinguish between buttons being more important than others depending on context by classifying as being primary or secondary.
=> Introducing a primary/secondary theme on buttons

components/shared/slideSelect/SlideSelect.tsx, styles/globals.css
https://reload.atlassian.net/browse/DDFBRA-423
This PR updates the mobile fonts to match the design
=> refactor: Adjust mobile typography to match figma design

components/paragraphs/ParagraphGoVideo/ParagraphGoVideo.stories.tsx, components/paragraphs/ParagraphGoVideo/ParagraphGoVideo.tsx, lib/graphql/generated/dpl-cms/graphql.tsx, lib/graphql/generated/fbi/graphql.tsx, lib/graphql/queries/page.dpl-cms.graphql
https://reload.atlassian.net/browse/DDFBRA-275
This PR updates the ParagraphGoVideo component with refactored data from CMS
=> feat: add embedVideo field to ParagraphGoVideo component and update GraphQL query

lib/config/dpl-cms/dplCmsConfig.ts
Correcting wrong copy/paste which was affecting unilogin configuration
=> Correcting wrong copy/paste

components/shared/authors/Authors.tsx, styles/utilities.css
https://reload.atlassian.net/browse/DDFBRA-422
This PR fixes a bug with underlined text (links).
-
=> Fix link underline

__tests__/refresh-token.test.ts, app/auth/callback/adgangsplatformen/loadUserToken.ts, app/auth/callback/adgangsplatformen/route.ts, lib/graphql/generated/dpl-cms/graphql.tsx, lib/graphql/queries/tokens.dpl-cms.graphql, lib/session/session.ts, middleware.ts
https://reload.atlassian.net/browse/DDFBRA-353
- Bringing back the NextJs middleware
- Use Adgangsplatformen user token expire value
- Add refresh functionality of Adgangsplatformen user token
Don' merge before this has been merged:
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2053
=> Refresh user tokens

components/pages/workPageLayout/WorkPageHeader.tsx
https://reload.atlassian.net/browse/DDFBRA-449
See title ^
=> refactor: Make workpage title smaller to prevent word breaks

components/shared/icon/Icon.tsx
https://reload.atlassian.net/browse/DDFBRA-459
This PR includes a fix for safari not showing icons correctly
=> fix: safari bug not showing icons

components/pages/workPageLayout/WorkPageButtons.tsx, components/shared/icon/Icon.tsx, components/shared/workCard/MaterialTypeIconWrapper.tsx
https://reload.atlassian.net/browse/DDFBRA-458
Minor text change
=> fix: change description for podcast and audiobook borrowing requirements text

components/shared/infoBox/InfoBoxDetails.tsx
https://reload.atlassian.net/browse/DDFBRA-450
Fixed text
=> fix: Rename "Omfang" to "Længde" in InfoBoxDetails component

app/auth/logout/helpers.ts, app/auth/logout/route.ts, lib/session/session.ts, middleware.ts
Please add a link to the issue being addressed by this change.
Makes sure that session is destroyed when expired
Also tidied up strurture of session and logout functions.
=> Makes sure that session is destroyed when expired

app/auth/callback/unilogin/helper.ts, lib/config/resolvers/auth.ts, lib/session/session.ts
https://reload.atlassian.net/browse/DDFBRA-519
This PR also allows DDF GO test users to login, which was previously prevented.
-
-
=> Fix go session type cookies

app/auth/callback/unilogin/helper.ts, app/auth/callback/unilogin/route.ts, app/error/login-failed/page.tsx, app/error/login-not-authorized/page.tsx, app/not-found.tsx, components/pages/errorPageLayout/ErrorPageLayout.tsx
https://reload.atlassian.net/browse/DDFBRA-533
- This PR handles has_licens which ensures the logged in user has the correct access
- Aligns all previous error pages to have same layout
=> Ddfbra 533 test om sti ls info service kan give adgang for brugerne

components/pages/searchPageLayout/SearchPageLayout.tsx
https://reload.atlassian.net/browse/DDFBRA-527
See title
=> fix: Adjust visibility breakpoints for search filters in SearchPageLayout

components/shared/darkModeToggle/DarkModeToggle.tsx, store/theme.store.ts
https://reload.atlassian.net/browse/DDFBRA-536
Read title ^
=> fix: theme store initialization without error in terminal

.github/workflows/e2e-test.yml
Please add a link to the issue being addressed by this change.
Please include a short description of the suggested change and the reasoning behind the approach you have chosen.
If your change affects the user interface you should include a screenshot of the result with the pull request.
If you have any further comments or questions for the reviewer them please add them here.
=> Bump Cypress Github Action

app/user/profile/DebuggingSession.tsx
=> Add server time so we can compare expire timestamps with current time

app/user/profile/ProfilePageLayout.tsx
https://reload.atlassian.net/browse/DDFBRA-508
This PR checks whether user is logged in on user page and if not redirects the user back to home page.
-
-
=> Redirect anonymous user out of user page

__tests__/env.test.ts, __tests__/helpers.ts, app/user/profile/ProfilePageLayout.tsx, components/pages/workPageLayout/WorkPageButton.tsx, components/pages/workPageLayout/WorkPageButtonsLoggedIn.tsx, components/pages/workPageLayout/WorkPageButtonsLoggedOut.tsx
https://reload.atlassian.net/browse/DDFBRA-202
https://reload.atlassian.net/browse/DDFBRA-203
This PR finetunes work page buttons.
-
-
=> Make sure correct buttons are primary themed

app/ap-service/[[...slug]]/route.ts, lib/helpers/ap-service.ts
Fix bug resolving all ap servie urls to fbi
...and also make sure cookies are not sent to services. The cookie header can ber rather big and is not needed.
=> Fix bug resolving all ap servie urls to fbi

components/pages/workPageLayout/helper.ts, components/shared/loanMaterialModal/LoanMaterialModal.tsx
https://reload.atlassian.net/browse/DDFBRA-547
This PR builds on top of #216 and fixes looking up quotas when loaning materials.
-
-
=> Fix quotas when loaning materials

app/pubhub/helper.ts, app/pubhub/v1/library/profile/(lib)/requests.ts, app/pubhub/v1/library/profile/(lib)/schemas.ts, app/pubhub/v1/library/profile/(lib)/types.ts, app/pubhub/v1/library/profile/route.ts, app/user/profile/LoanSlider.tsx, app/user/profile/ProfilePageLayout.tsx, app/user/profile/QuotasSection.tsx, app/user/profile/UserLoans.tsx, components/pages/workPageLayout/helper.ts, components/shared/loanMaterialModal/LoanMaterialModal.tsx, lib/rest/publizon/useGetV1LibraryProfile.ts, lib/soap/publizon/v2_7/generated/getlibraryinfo/client.ts, lib/soap/publizon/v2_7/generated/getlibraryinfo/definitions/GetLibraryProfile.ts, lib/soap/publizon/v2_7/generated/getlibraryinfo/definitions/GetLibraryProfileResponse.ts, lib/soap/publizon/v2_7/generated/getlibraryinfo/definitions/GetLibraryProfileResult.ts, lib/soap/publizon/v2_7/generated/getlibraryinfo/definitions/InstitutionTags.ts, lib/soap/publizon/v2_7/generated/getlibraryinfo/index.ts, lib/soap/publizon/v2_7/generated/getlibraryinfo/ports/GetlibraryinfoSoap.ts, lib/soap/publizon/v2_7/generated/getlibraryinfo/ports/GetlibraryinfoSoap12.ts, lib/soap/publizon/v2_7/generated/getlibraryinfo/services/Getlibraryinfo.ts, lib/soap/publizon/v2_7/wsdl/getlibraryinfo.wsdl, scripts/wsdl-tsclient/publizon-wsdl-codegen.ts
https://reload.atlassian.net/browse/DDFBRA-547
This PR:
- adds a new local Pubhub endpoint - v1/library/profile
- reworks the quota logic on user page (previous implementation was incorrect)
-
- reworking quotas when user is loaning will come in a separate PR
=> Fix quotas

app/ap-service/[[...slug]]/route.ts, lib/config/resolvers/search.ts, package.json, yarn.lock
https://reload.atlassian.net/browse/DDFBRA-560
- Updated comments and removed fetch-to-curl package
=> Ddfbra 560 filtrer uonskede materialetyper ud i sogeresultat kald

components/pages/workPageLayout/helper.ts, lib/machines/search/queries.ts
https://reload.atlassian.net/browse/DDFBRA-535
Minor fixes to filter out unwanted materialtypes
=> fix: material type filtering logic and remove unwanted material types

components/pages/workPageLayout/helper.ts, components/shared/loanMaterialModal/LoanMaterialModal.tsx
https://reload.atlassian.net/browse/DDFBRA-537
This PR makes it impossible to loan more than 30 blue titles (costFree).
-
-
=> Disallow more than 30 blue title loans

package.json
Please add a link to the issue being addressed by this change.
Please include a short description of the suggested change and the reasoning behind the approach you have chosen.
If your change affects the user interface you should include a screenshot of the result with the pull request.
If you have any further comments or questions for the reviewer them please add them here.
=> Use `tsx` instead og `ts-node` to run post process script

components/pages/searchPageLayout/SearchResults.tsx, components/paragraphs/MaterialSlider/MaterialSlider.tsx, components/shared/workCard/WorkCard.tsx, components/shared/workCard/WorkCardStackedWithCaption.tsx
https://reload.atlassian.net/browse/DDFBRA-575
This PR makes sure that the best representation manifestation is a available manifestation type.
=> feat: refactor work card component to handle best representation manifestation + simplified workCard component

app/pubhub/(lib)/helper.ts, app/pubhub/v1/library/profile/route.ts, app/pubhub/v1/user/loans/[identifier]/route.ts, app/pubhub/v1/user/loans/route.ts
https://reload.atlassian.net/browse/DDFBRA-528
This PR cleans out some TS todos.
-
-
=> Fix todo in Pubhub API code

lib/config/dpl-cms/dplCmsConfig.ts
https://reload.atlassian.net/browse/DDFBRA-572
Prevent build errors when fetching dplcms config
Make sure that error is catched so it does not block the build process
=> Prevent build errors when fetching dplcms config

app/(pages)/user/profile/LoanSlider.tsx, app/(pages)/user/profile/ProfilePageLayout.tsx, components/pages/searchPageLayout/SearchPageLayout.tsx, components/shared/loanMaterialModal/LoanMaterialModal.tsx, components/shared/sheet/LoginSheet.tsx
https://reload.atlassian.net/browse/DDFBRA-588
This PR corrects some texts around the app
-
-
=> Correct various texts around the app

components/pages/articlePageLayout/ArticlePageLayout.tsx, components/pages/basicPageLayout/BasicPageLayout.tsx
https://reload.atlassian.net/browse/DDFBRA-595
=> fix: missing paragraphs not showing layouts

lib/helpers/helper.metadata.ts
https://reload.atlassian.net/browse/DDFBRA-579
This PR changes the tab title in the browser.
-
-
=> Change tab title

app/(pages)/user/profile/LoanSlider.tsx, app/(pages)/user/profile/QuotasSection.tsx, app/(routes)/pubhub/v1/user/loans/(lib)/requests.ts, app/(routes)/pubhub/v1/user/loans/(lib)/schemas.ts, app/(routes)/pubhub/v1/user/loans/(lib)/types.ts, lib/soap/publizon/v2_7/generated/getfriendlycardnumber/client.ts, lib/soap/publizon/v2_7/generated/getfriendlycardnumber/definitions/GetFriendlyCardnumber.ts, lib/soap/publizon/v2_7/generated/getfriendlycardnumber/definitions/GetFriendlyCardnumberResponse.ts, lib/soap/publizon/v2_7/generated/getfriendlycardnumber/definitions/GetFriendlyCardnumberResult.ts, lib/soap/publizon/v2_7/generated/getfriendlycardnumber/index.ts, lib/soap/publizon/v2_7/generated/getfriendlycardnumber/ports/GetfriendlycardnumberSoap.ts, lib/soap/publizon/v2_7/generated/getfriendlycardnumber/ports/GetfriendlycardnumberSoap12.ts, lib/soap/publizon/v2_7/generated/getfriendlycardnumber/services/Getfriendlycardnumber.ts, lib/soap/publizon/v2_7/wsdl/getfriendlycardnumber.wsdl, scripts/wsdl-tsclient/publizon-wsdl-codegen.ts
https://reload.atlassian.net/browse/DDFBRA-613
This PR introduces the following enhancements:
- **Consistent Data Return**: Ensures that the ⁠getLibraryUserOrderListRequest in the local adapter always returns data. This change aims to prevent any potential breaks in the frontend functionality. 
- **Fallback Default Object**: In cases where the data returned by ⁠getLibraryUserOrderList is empty, a fallback default object has been implemented. This object includes a specific call to ⁠getFriendlyCardNumber, ensuring that necessary information is still accessible.
=> Ddfbra 613 udvid lokal adapter til at hente bruger data gennem nye saop kald pa unilogin brugere

app/(pages)/user/profile/LoanCard.tsx, components/shared/workCard/MaterialTypeIconWrapper.tsx, styles/globals.css, styles/theme.css
https://reload.atlassian.net/browse/DDFBRA-608
=> fix: opacity issue on loanCards

lagoon/start.sh
https://reload.atlassian.net/browse/DDFBRA-719
=> Use potential www in go urls in startup script

lib/graphql/fetchers/dpl-cms.fetcher.ts
If something goes wrong we would like to know what.
=> Add console error to dpl cms fetcher

.github/workflows/publish-source.yml
Allow either our versioning that we use in other DPL projects: [digits].[digits].[digits]
or
a tag used for testing/demo etc.:
[a descriptive name eg. "test"]-[current date].[a digit]
=> Change go version format

app/(routes)/auth/callback/unilogin/route.ts, app/(routes)/pubhub/v1/library/profile/route.ts, app/(routes)/pubhub/v1/user/loans/[identifier]/route.ts, app/(routes)/pubhub/v1/user/loans/route.ts, lib/graphql/fetchers/dpl-cms.fetcher.ts, lib/helpers/bearer-token.ts, lib/helpers/user-token.ts, lib/rest/publizon/local-adapter/mutator/fetcher.ts, lib/session/session.ts
=> feat: add context for error messages

.github/dependabot.yml, docs/expexted-session-behaviour.md, package.json, yarn.lock
https://reload.atlassian.net/browse/DDFBRA-729
- Added dependabot groupings 
- Changed the next.js version to a fixed version number
=> Ddfbra 729 opsaetning af dependabot

components/global/footer/Footer.tsx
https://reload.atlassian.net/browse/DDFSAL-264
This PR changes links in the footer.
=> Ddfsal 264 aendring af links i footer

__tests__/middleware.test.ts, __tests__/revalidating-cache.test.ts
https://reload.atlassian.net/browse/DDFSAL-328
=> fix: ci warnings spamming logs in the terminal

components/pages/workPageLayout/WorkPageLayout.tsx, components/pages/workPageLayout/helper.ts
Please add a link to the issue being addressed by this change.
https://github.com/danskernesdigitalebibliotek/dpl-go/pull/378
=> 2025.33.1 Important change

.github/dependabot.yml
https://reload.atlassian.net/browse/DDFSAL-320
This PR updates dependabot configuration to be streamlined with the documentation
=> fix: update dependabot configuration to streamline with the documentation

cypress/support/commands.ts, cypress/support/setupNodeEvents/index.ts
=> Add cypress command for setting a unilogin/adgangsplatformen session

app/(routes)/auth/callback/unilogin/helper.ts, app/(routes)/auth/callback/unilogin/route.ts, app/(routes)/auth/login/unilogin/route.ts
https://reload.atlassian.net/browse/DDFSAL-380
This PR enhances error logging in unilogin authorization flow
=> Ddfsal 376 pkce validering fejler ifm unilogin

.github/dependabot.yml
=> chore(deps): remove cypress patterns from dependabot configuration

app/(routes)/auth/callback/unilogin/route.ts, app/(routes)/auth/login/unilogin/route.ts
[DDFSAL-387](https://reload.atlassian.net/browse/DDFSAL-387)
This PR makes sure to navigate the user to the profile page from the callback url if already logged in.
=> fix: redirect logged-in users to profile page

.github/dependabot.yml
=> chore(deps): update eslint-plugin-storybook version constraint 
